// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: circle-240

#include "ui/common.h"

#define ui_small_plot (ui.screen)
#define ui_TempIn1 (ui.temp_in)
#define ui_TempOut1 (ui.temp_out)
#define ui_HumidityIn1 (ui.humidity_in)
#define ui_HumidityOut1 (ui.humidity_out)
#define ui_PressureIn1 (ui.pressure_in)
#define ui_PressureOut1 (ui.pressure_out)
#define ui_VocIn1 (ui.voc_in)
#define ui_VocOut1 (ui.voc_out)
#define ui_VocArc1 (ui.voc_arc)
#define ui_TempArc1 (ui.temp_arc)
#define ui_Chart1 (ui.chart)
#define ui_XAxisScale1 (ui.chart_x_axis_scale)
#define ui_FanPower1 (ui.fan_power)
#define ui_FanRPM1 (ui.fan_rpm)
#define ui_TouchOverlay1 (ui.touch_overlay)
#define ui_FanPowerArc1 (ui.fan_power_arc)

NevermoreDisplayUI nevermore_ui_screen_circle_240_small_plot() {
    lv_obj_t* ui_FanBox1;

    NevermoreDisplayUI ui = {0};

    ui_small_plot = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_small_plot, LV_OBJ_FLAG_SCROLLABLE);  /// Flags
    lv_obj_set_style_bg_color(ui_small_plot, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_small_plot, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    /* inner ring, left half: VOC index, coloured by zone (clean / elevated / fan should be running) */
    ui_VocArc1 = lv_arc_create(ui_small_plot);
    lv_obj_clear_flag(ui_VocArc1, LV_OBJ_FLAG_CLICKABLE);  /// Flags
    lv_obj_set_width(ui_VocArc1, lv_pct(86));
    lv_obj_set_height(ui_VocArc1, lv_pct(86));
    lv_obj_set_align(ui_VocArc1, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_VocArc1, 0, 500);
    lv_arc_set_bg_angles(ui_VocArc1, 115, 270);
    lv_obj_set_style_arc_width(ui_VocArc1, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_VocArc1, lv_color_hex(0x303030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_VocArc1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_VocArc1, 12, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_VocArc1, lv_color_hex(0x00FF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_VocArc1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VocArc1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    /* inner ring, right half: temperature 10..40°C, ramping blue -> red.
       REVERSE mode anchors the indicator at the arc's end angle instead of its start,
       which is what makes this half grow from the bottom up like the VOC half — a plain
       arc would fill clockwise from the top downwards. */
    ui_TempArc1 = lv_arc_create(ui_small_plot);
    lv_obj_clear_flag(ui_TempArc1, LV_OBJ_FLAG_CLICKABLE);  /// Flags
    lv_obj_set_width(ui_TempArc1, lv_pct(86));
    lv_obj_set_height(ui_TempArc1, lv_pct(86));
    lv_obj_set_align(ui_TempArc1, LV_ALIGN_CENTER);
    lv_arc_set_mode(ui_TempArc1, LV_ARC_MODE_REVERSE);
    lv_arc_set_range(ui_TempArc1, 10, 40);
    lv_arc_set_bg_angles(ui_TempArc1, 270, 65);
    lv_obj_set_style_arc_width(ui_TempArc1, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_TempArc1, lv_color_hex(0x303030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_TempArc1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_TempArc1, 12, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_TempArc1, lv_color_hex(0x0000FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_TempArc1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TempArc1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_TempOut1 = lv_label_create(ui_small_plot);
    lv_obj_set_align(ui_TempOut1, LV_ALIGN_CENTER);
    lv_obj_set_x(ui_TempOut1, 40);
    lv_obj_set_y(ui_TempOut1, -40);
    lv_label_set_text(ui_TempOut1, "---°C");
    lv_obj_set_style_text_color(ui_TempOut1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TempOut1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TempOut1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumidityOut1 = lv_label_create(ui_small_plot);
    lv_obj_set_align(ui_HumidityOut1, LV_ALIGN_CENTER);
    lv_obj_set_x(ui_HumidityOut1, -40);
    lv_obj_set_y(ui_HumidityOut1, -40);
    lv_label_set_text(ui_HumidityOut1, "---%");
    lv_obj_set_style_text_color(ui_HumidityOut1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HumidityOut1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HumidityOut1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VocOut1 = lv_label_create(ui_small_plot);
    lv_obj_set_align(ui_VocOut1, LV_ALIGN_CENTER);
    lv_obj_set_x(ui_VocOut1, 0);
    lv_obj_set_y(ui_VocOut1, 10);
    lv_label_set_text(ui_VocOut1, "---");
    lv_obj_set_style_text_color(ui_VocOut1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VocOut1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VocOut1, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    /* stacked, not side-by-side: a 5-digit RPM would run past the ring if it shared a row */
    ui_FanBox1 = lv_obj_create(ui_small_plot);
    lv_obj_remove_style_all(ui_FanBox1);
    lv_obj_set_width(ui_FanBox1, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_FanBox1, LV_SIZE_CONTENT);  /// 50
    lv_obj_set_x(ui_FanBox1, 0);
    lv_obj_set_y(ui_FanBox1, 70);
    lv_obj_set_align(ui_FanBox1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_FanBox1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_FanBox1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_pad_row(ui_FanBox1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_clear_flag(ui_FanBox1, LV_OBJ_FLAG_SCROLLABLE);  /// Flags

    ui_FanPower1 = lv_label_create(ui_FanBox1);
    lv_obj_set_width(ui_FanPower1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FanPower1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_align(ui_FanPower1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FanPower1, "0%");
    lv_obj_set_style_text_color(ui_FanPower1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FanPower1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FanPower1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FanRPM1 = lv_label_create(ui_FanBox1);
    lv_obj_set_width(ui_FanRPM1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FanRPM1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_align(ui_FanRPM1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FanRPM1, "0");
    lv_obj_set_style_text_color(ui_FanRPM1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FanRPM1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FanRPM1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    /* long-press anywhere clears/sets the fan override; sits below the ring so the ring still drags */
    ui_TouchOverlay1 = lv_obj_create(ui_small_plot);
    lv_obj_remove_style_all(ui_TouchOverlay1);
    lv_obj_set_width(ui_TouchOverlay1, lv_pct(100));
    lv_obj_set_height(ui_TouchOverlay1, lv_pct(100));
    lv_obj_set_align(ui_TouchOverlay1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TouchOverlay1, LV_OBJ_FLAG_SCROLLABLE);  /// Flags

    /* outer ring: fan power. Created last so it sits above the overlay and can actually be dragged. */
    ui_FanPowerArc1 = lv_arc_create(ui_small_plot);
    lv_obj_add_flag(ui_FanPowerArc1, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_set_width(ui_FanPowerArc1, lv_pct(100));
    lv_obj_set_height(ui_FanPowerArc1, lv_pct(100));
    lv_obj_set_align(ui_FanPowerArc1, LV_ALIGN_CENTER);
    lv_obj_set_scroll_dir(ui_FanPowerArc1, LV_DIR_TOP);
    lv_arc_set_range(ui_FanPowerArc1, 0, 200);
    lv_arc_set_bg_angles(ui_FanPowerArc1, 115, 65);
    lv_obj_set_style_arc_width(ui_FanPowerArc1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_FanPowerArc1, lv_color_hex(0x303030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_FanPowerArc1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_FanPowerArc1, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_FanPowerArc1, lv_color_hex(0x00FFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_FanPowerArc1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_opa(ui_FanPowerArc1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_FanPowerArc1, lv_color_hex(0xFFFF00), LV_PART_KNOB | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_FanPowerArc1, 255, LV_PART_KNOB | LV_STATE_PRESSED);

    return ui;
}
